language: swift
xcode_workspace: Implementation/App/Travlendar/Travlendar.xcworkspace # path to your xcodeproj folder
xcode_scheme: Tests
osx_image: xcode9.1
podfile: Implementation/App/Travlendar/Podfile

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 6eee328f-741e-4c4d-975b-dc96ee35d48c