coverage:
  precision: 2
  round: down
  range: "70...100"
  ignore:
    - alloy/*
    - Assets/*
    - DD/*
    - DeliveryFolder/*
    - Design/*
    - ImageBorderAdder/*
    - RASD/*
    - Requirements/*
    - Implementation/Server/node_modules/*
    - readme.md
  status:
    patch:
      default:
        if_no_uploads: error
    changes: true
    project:
      default:
        target: auto
        if_no_uploads: error
comment: false